### ISSUE TITLE
[Epic] User inputs required, Pre-populated information, selectable options

### ISSUE THREAD

**Issue by BatchOfAllTrades** [OptiCut/OptiCut#14]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  User
**I want**  a combination of pre-populated information, selectable options, and data to input before executing the plugin
**so that**  the plugin creates accurate cut layouts with attention to the tools I plan to use to cut the material, and the stock material sizes I plan to use, while saving time with setup.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Scenario 1_  Pre-populated information:
 - The plugin should take all bodies from the design and lay them out for efficient cutting
     - The plugin should be able to recognize the thickness of any given body and not put bodies of different thicknesses into the same cutting layout.
 - The plugin should recognize non-rectangular bodies and fit them into a rectangular area for rough cutting.
 - Grain direction is automatically set to along the longest edge of a body (User input can change this setting {see below})
* _Scenario 2_  Selectable options:
 - Kerf (blad thickness)
   - Full kerf
   - Thin kerf
   - User input {see below}
 - Plywood/Material
   - 4' x 8' sheets
   - 5' x 5' sheets
   - 2' x 4' sheets
   - User input {see below}
* _Scenario 3_ User input options:
 - Grain direction can be manually set to run in a different direction than along the longest edge.
 - Kerf can be manually entered if using something other than a table saw to make cuts.
 - Available material can be manually entered.  This would allow for using scrap materials a woodworker might have on hand.  This should be labeled "Material on hand" so as to not add to "Material needed for project" which is produced by the plugin.
