### ISSUE TITLE
Modify Repository Documentations

### ISSUE THREAD

**Issue by cdinh92** [OptiCut/OptiCut#32]
# Documentation
As contributors, our aim is to enhance the documentation within our repository to provide easy access to essential project information for potential contributors. This ensures that anyone interested can readily grasp the details they need to continue working on the project seamlessly.
## Task Lists
- [x] Update the README.md file with more information and instructions
- [x] Update the GitHub Page link inside the README file
- [x] Add copyrights/ licenses to our product assets #31 
- [x] Upload all the works with documentations for future contributors
