### ISSUE TITLE
Update the Presentation Slides

### ISSUE THREAD

**Issue by cdinh92** [OptiCut/OptiCut#33]
# Update the Presentation Slides
Based on the discussion with Professor Jody on Thursday, April 25, 2024, we have to update the slides to meet the requirements and prepare for the presenting day.
## Task Lists:
- [ ] Instead of weeks, Jody wants us to mention how many total hours the team spent on each developing phrase. That would be a better idea if we could estimate the total time each person spent on the project.
- [ ] The metrics look very suspicious since Jody wants to know exactly how big the project is (code parts, total code lines,...) so he will know exactly how and what the percentage numbers represent.
- [ ] Jody also needs the metrics for the product presentation: run time, how effective the algorithm is, and loading time,...
- [ ] I attended "Free and Open Source Software" with Jody, so I understand that we have to take care of the copyrights and licenses #31 
- [ ] We have to focus the documentation on our repo (README.dm, any .txt files) as we're done with the project soon #32
